runtime: python
runtime_config:
  python_version: 3
env: flex
env_variables:
  NODE_ENV: "development"

entrypoint: gunicorn -b :$PORT app:app  --timeout 90

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7